# Use postgres/example user/password credentials

services:

  app: 
    build: 
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npm","start"]
    env_file:
      - ./.env
    ports: 
      - 8080:8080

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
